version: "2.2"

services:
    help:
        build: .
        ports:
            - '8084:80'
        stdin_open: true
        tty: true
        volumes:
            - ./src:/var/www/html
            - ./logs:/var/log/apache2
            - ./flag1:/flag1
            - ./flag2:/flag2
            - ./flag3:/flag3